---
title: "Notes"
output: html_notebook
---

### 29.11.2023

1. I have started by renaming a few attributes to make them better for the R language and more comprehensible to the readers.
2. I have included a new category (**Cortex.y.n**) in case we need to create two macro-categories.
3. I have excluded **Square**, **Cat**, and all attributes after the retouch. They should be renamed following the steps listed in the script *datasets.reshaped* and included in the main dataset.
4. The file *attribute.list* contains attributes and uncertainties colored in red.
5. What is now missing is the renaming of the categories within each attribute to make statistical investigation smoother. This can be done following the example provided below:
```{r}
# mutate(Cortex.y.n = recode(Cortex.y.n, Extensive = "Yes", Full = "Yes", Semi = "Yes"))
# Cortex.y.n = this is the name of the attribute
# Then it goes the old name and, after the equal symbol (=), the "new name"
```

### 06.12.2023

1. I have included the dataset from FUmane, taking into account the external area of the excavation up to the lines of square 80s. This is the same sampling I used for my paper in JASs.
2. Important note: the attribute twisting/torsion is separated in my case. This needs to be merged in case. For the time being, in order to keep it, I have created an empty column for the other sites and include the torsion attribute of Fumane. This is divided into 0 (no torsion), 1L or 1R (sligthly twisted to the Left or Right), 2L or 2R (twisted to the Left or Right).
3. The attribute Negative.types is a bit tricky for me because I only recorded if there were bladelet scars on the dorsal faces of blades (with TRUE and FALSE statements).
4. In my case, Dorsal.scar.1 and Dorsal.scar.2 is the same (duplicated columns) because I have another attribute in my original dataset that is very complex and difficult to reshape easily. We need just to change my entries in the simplified one with the same attributes used for Rom, Ansab, and CTS.
5. In my case, the Symmetry attribute refers to the symmetry of the cross section. I think it's the same for the other but it is important to notice it.
6. Certain attributes, such as Bulb, are a bit different in my case because I first noted if it was present or not (TRUE or FALSE, see raw dataset), and then I described the type of bulb. For the data quantification it will be needed to do a filter with tidyverse selecting only the proximal and complete items and then quantify the type of bulb. However, it will be needed to add the attribute *absent* for the ones where the bulb/lip is missing. If I do not fo it, I will need a reminder!

### 11.12.2023 Jacopo Gennai

I changed the title to a more generic "Notes". From this day on write your name after the day of the change.
